### ISSUE TITLE
Carbon Footprint

### ISSUE THREAD

**Issue by mgifford** [AjuntamentdeBarcelona/ict-procurement-bcn-en#4]
In reaction to this article on procurement - https://medium.com/openconcept-stories/innovation-procurement-and-sustainability-c9e8f887715b

I was pointed to your Ethical Digital Standards. 

Love what you are doing here! 

Given the current climate crisis and global commitments to the Paris Agreement are there any efforts to put CO2 accounting into this?

Thanks!

**Comment by imingueza** [comment]
Dear Mike,
Thank you for your contribution and for sharing the article, it is really interesting. For the moment, we don’t contemplate to include in this specific guide how directly deal with CO2 reduction.

But there is another government measures at city council level that have been won the [Procura+ Award](http://www.procuraplus.org/awards/) for Procurement Initiative of the Year 2018. Barcelona City Council has passed a Municipal Decree (S1/D/2017-1271, of 24 April, available in Catalan [here)](https://bcnroc.ajuntament.barcelona.cat/jspui/bitstream/11703/101966/3/Contractaci%c3%b3_p%c3%bablica_sostenible.pdf) that makes Sustainable Public Procurement (SPP) mandatory. This has an effect on more than 50,000 tenders annually, covering a spend of €1.1bn.
The SPP objectives are geared toward four key aspects: to improve social and labour conditions, to promote the participation of SMEs and the social economy, to protect the environment, and to foster innovation. Getting to this stage has been an incremental process with Barcelona championing sustainability and innovation in procurement since 2001. So far, the strategic use of procurement has resulted in improved working conditions in newly awarded contracts, a significant reduction of resource and electricity consumption, and not least annual savings of more than 36,000 tonnes of CO2 due to the purchase of 100% renewable energy.
You can find more information in English [here.](https://ajuntament.barcelona.cat/contractaciopublica/en/documents)

Also, Barcelona City Council will work towards the [UN’s Sustainable Development Goals (SDGs)](https://www.barcelona.cat/infobarcelona/en/city-commitment-to-the-2030-agenda_853804.html).

So, it exists at least a general framework of Sustainable Public Procurement that ICT providers have to be aware.

**Comment by mgifford** [comment]
Thanks @imingueza this is a great example for other government agencies. Really happy that you are able to answer me in English & have information on the sustainable public procurement in English too.
